// web-next/apps/web/app/community/page.tsx
import { Button, Eyebrow, Reveal, Section } from "@nativelink/ui";

export const metadata = { title: "Community" };

const channels = [
  {
    title: "Read the docs",
    body: "Setup guides, architecture deep-dives, and reference for every build system.",
    href: "/docs",
    label: "Open docs",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">
        <path d="M4 4h12a2 2 0 0 1 2 2v14H6a2 2 0 0 1-2-2V4Z" strokeLinejoin="round" />
        <path d="M8 8h6M8 12h6M8 16h4" strokeLinecap="round" />
      </svg>
    ),
  },
  {
    title: "Join the Slack",
    body: "Talk to other operators, share configs, and get help from the core team.",
    href: "https://forms.gle/LtaWSixEC6bYi5xF7",
    label: "Join Slack",
    icon: (
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true">
        <rect x="3" y="11" width="6" height="2" rx="1" />
        <rect x="11" y="15" width="2" height="6" rx="1" />
        <rect x="15" y="11" width="6" height="2" rx="1" />
        <rect x="11" y="3" width="2" height="6" rx="1" />
      </svg>
    ),
  },
  {
    title: "Clone the repo",
    body: "NativeLink is open source. File issues, send PRs, or star us on GitHub.",
    href: "https://github.com/tracemachina/nativelink",
    label: "View on GitHub",
    icon: (
      <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">
        <path d="M12 .5C5.65.5.5 5.65.5 12c0 5.08 3.29 9.39 7.86 10.91.58.11.79-.25.79-.56v-2.01c-3.2.7-3.87-1.36-3.87-1.36-.52-1.34-1.28-1.69-1.28-1.69-1.05-.71.08-.7.08-.7 1.16.08 1.77 1.19 1.77 1.19 1.03 1.76 2.7 1.25 3.36.96.1-.74.4-1.25.73-1.54-2.55-.29-5.23-1.28-5.23-5.68 0-1.25.45-2.28 1.19-3.08-.12-.29-.51-1.46.11-3.04 0 0 .97-.31 3.18 1.18.92-.26 1.91-.39 2.89-.39s1.97.13 2.89.39c2.21-1.49 3.18-1.18 3.18-1.18.62 1.58.23 2.75.11 3.04.74.8 1.19 1.83 1.19 3.08 0 4.41-2.69 5.39-5.25 5.67.41.36.78 1.06.78 2.14v3.17c0 .31.21.68.8.56 4.57-1.52 7.86-5.83 7.86-10.91C23.5 5.65 18.35.5 12 .5Z" />
      </svg>
    ),
  },
];

export default function CommunityPage() {
  return (
    <>
      {/* HERO */}
      <Section width="default" className="pt-24 pb-16 md:pt-32">
        <Reveal>
          <div className="mx-auto max-w-[820px] text-center">
            <Eyebrow className="mb-5">Community</Eyebrow>
            <h1 className="text-balance text-4xl font-bold leading-[1.1] tracking-tight md:text-6xl">
              Join the people building NativeLink.
            </h1>
            <p className="mx-auto mt-6 max-w-[640px] text-lg leading-relaxed text-muted">
              Operators, contributors, and the engineers who build NativeLink — all in
              the same room.
            </p>
          </div>
        </Reveal>
      </Section>

      {/* CHANNELS */}
      <Section width="default" className="pb-24">
        <div className="grid gap-6 md:grid-cols-3">
          {channels.map((c, i) => (
            <Reveal key={c.title} delay={i * 0.05}>
              <a
                href={c.href}
                target={c.href.startsWith("http") ? "_blank" : undefined}
                rel={c.href.startsWith("http") ? "noreferrer" : undefined}
                className="group flex h-full flex-col rounded-md border-2 border-border bg-surface/50 p-8 transition-colors hover:border-foreground hover:bg-foreground hover:text-background"
              >
                <span className="mb-6 inline-flex h-12 w-12 items-center justify-center [&_svg]:h-7 [&_svg]:w-7">
                  {c.icon}
                </span>
                <h3 className="text-xl font-semibold leading-tight">{c.title}</h3>
                <p className="mt-3 text-base leading-relaxed text-muted-foreground group-hover:text-background/80">
                  {c.body}
                </p>
                <span className="mt-6 inline-flex items-center gap-1 font-mono text-sm">
                  {c.label} <span aria-hidden="true">→</span>
                </span>
              </a>
            </Reveal>
          ))}
        </div>
      </Section>

      {/* CONTRIBUTORS */}
      <Section
        width="narrow"
        className="border-t border-[rgb(var(--nl-color-accent-line))]/40 py-24 text-center"
      >
        <Reveal>
          <Eyebrow className="mb-5">Thank you</Eyebrow>
          <h2 className="text-balance text-3xl font-bold leading-[1.15] md:text-5xl">
            We love our contributors.
          </h2>
          <p className="mx-auto mt-6 max-w-[600px] text-base leading-relaxed text-muted md:text-lg">
            As a small token of appreciation, we'd love to send something special to
            active NativeLink community members and contributors. Fill out the form
            and our team will be in touch.
          </p>
          <div className="mt-8 flex justify-center">
            <Button size="lg" asChild>
              <a href="https://forms.gle/LtaWSixEC6bYi5xF7" target="_blank" rel="noreferrer">
                Fill out the form
              </a>
            </Button>
          </div>
        </Reveal>
      </Section>
    </>
  );
}

// web/platform/src/components/qwik/pages/community.tsx
import { component$ } from "@builder.io/qwik";

import { GitHub, Slack } from "../../media/icons/icons.tsx";

export const CommunityPage = component$(() => {
  return (
    <main class="bg-[rgb(248,247,244)] min-h-screen">
      {/* Hero Section */}
      <div class="section-spacing-major section-divider">
        <div class="max-w-6xl mx-auto px-6">
          <h1 class="text-5xl md:text-7xl font-bold text-black mb-8">
            Join our community
          </h1>

          {/* Connect Cards */}
          <div class="grid md:grid-cols-3 gap-8 pt-20 md:pt-24">
            <a
              href="/docs/introduction/setup"
              aria-label="Read the Docs"
              class="card-warm p-8 flex flex-col gap-6 hover:-translate-y-1 transition-all duration-200 no-underline items-center text-center"
            >
              <svg
                class="w-16 h-16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="rgb(100,100,255)"
                stroke-width="2"
                aria-hidden="true"
                focusable="false"
              >
                <rect x="2" y="3" width="20" height="18" rx="2" />
                <path d="M8 7h8M8 11h8M8 15h4" />
              </svg>
              <h3 class="text-2xl font-bold text-black">Read the Docs</h3>
            </a>

            <a
              href="https://forms.gle/LtaWSixEC6bYi5xF7"
              aria-label="Join our Slack"
              class="card-warm p-8 flex flex-col gap-6 hover:-translate-y-1 transition-all duration-200 no-underline items-center text-center"
            >
              <div class="flex-shrink-0">
                <Slack />
              </div>
              <h3 class="text-2xl font-bold text-black">Join our Slack</h3>
            </a>

            <a
              href="https://github.com/tracemachina/nativelink"
              aria-label="Clone the Repo"
              class="card-warm p-8 flex flex-col gap-6 hover:-translate-y-1 transition-all duration-200 no-underline items-center text-center"
            >
              <div class="flex-shrink-0">
                <GitHub />
              </div>
              <h3 class="text-2xl font-bold text-black">Clone the Repo</h3>
            </a>
          </div>
        </div>
      </div>

      {/* Events section intentionally hidden. */}

      {/* Appreciation Section */}
      <div class="section-spacing-major">
        <div class="max-w-3xl mx-auto px-6 text-center">
          <h2 class="text-3xl md:text-5xl font-bold text-black mb-6">
            We Love Our Community
          </h2>
          <p class="text-lg text-[rgb(60,60,60)] leading-relaxed mb-8">
            To say thank you to our NativeLink contributors and community
            members, we’d love to send you something special as a small token of
            appreciation. Simply fill out the form below, our team will verify
            your details, and send something special your way.
          </p>
          <a
            href="https://forms.gle/LtaWSixEC6bYi5xF7"
            class="inline-flex bg-black text-white hover:bg-[rgb(40,40,40)] transition-colors duration-200 px-12 min-h-[48px] rounded-interactive justify-center items-center border-2 border-black font-semibold"
          >
            Fill out the form
          </a>
        </div>
      </div>
    </main>
  );
});
