// web-next/apps/web/app/company/page.tsx
import {
  Button,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  CardTitle,
  Divider,
  Eyebrow,
  Reveal,
  Section,
} from "@nativelink/ui";

export const metadata = { title: "Company" };

const contactCards = [
  {
    title: "Media kit",
    body: "Download our logos, branding guidelines, and other press resources.",
    cta: { label: "Download", href: "https://drive.google.com/drive/folders/" },
    variant: "outline" as const,
  },
  {
    title: "General inquiries",
    body: "Have a question or comment? We'd love to hear from you.",
    cta: { label: "Contact us", href: "mailto:contact@nativelink.com" },
    variant: "outline" as const,
  },
  {
    title: "Sales inquiries",
    body: "Want to know if NativeLink is right for your team? Our sales engineers can help.",
    cta: { label: "Talk to sales", href: "mailto:hello@nativelink.com" },
    variant: "primary" as const,
  },
];

export default function CompanyPage() {
  return (
    <>
      {/* HERO */}
      <Section width="default" className="pt-24 pb-16 md:pt-32">
        <Reveal>
          <div className="mx-auto max-w-[820px] text-center">
            <Eyebrow className="mb-5">Company</Eyebrow>
            <h1 className="text-balance text-4xl font-bold leading-[1.1] tracking-tight md:text-6xl">
              NativeLink is built by Trace Machina.
            </h1>
            <p className="mx-auto mt-6 max-w-[640px] text-lg leading-relaxed text-muted">
              Our mission is to accelerate the reindustrialization of the world in the
              machine age.
            </p>
          </div>
        </Reveal>
      </Section>

      {/* MISSION */}
      <Section width="narrow" className="pb-24">
        <Reveal>
          <div className="space-y-6 text-balance text-center text-base leading-relaxed text-muted md:text-lg">
            <p>
              We empower engineers to build the future of technology by making advanced
              build and simulation processes that move at machine speed.
            </p>
            <p>
              Our products amplify the rate at which companies can innovate across
              mission-critical industries — from semiconductors and advanced robotics to
              autonomous vehicles, artificial intelligence research, life sciences, and
              financial services.
            </p>
            <p>
              Our commitment is to amplify execution across any environment, ensuring
              that developers can focus on creating transformative technologies that
              drive forward progress on behalf of humanity.
            </p>
          </div>
        </Reveal>
      </Section>

      <Section width="default" className="py-0">
        <Divider inset />
      </Section>

      {/* CONTACT CARDS */}
      <Section width="default" className="py-24">
        <Reveal>
          <div className="mx-auto mb-12 max-w-[680px] text-center">
            <Eyebrow className="mb-4">Get in touch</Eyebrow>
            <h2 className="text-3xl font-bold leading-[1.15] md:text-5xl">
              Have questions or need assistance?
            </h2>
            <p className="mt-5 text-base leading-relaxed text-muted md:text-lg">
              Reach out for general inquiries, sales conversations, or anything else —
              we usually reply within a day.
            </p>
          </div>
        </Reveal>
        <div className="grid gap-6 md:grid-cols-3">
          {contactCards.map((c, i) => (
            <Reveal key={c.title} delay={i * 0.05}>
              <Card className="flex h-full flex-col">
                <CardHeader>
                  <CardTitle>{c.title}</CardTitle>
                </CardHeader>
                <CardBody>{c.body}</CardBody>
                <CardFooter className="mt-auto">
                  <Button
                    asChild
                    variant={c.variant}
                    size="md"
                    className={c.variant === "outline" ? "w-full" : "w-full"}
                  >
                    <a
                      href={c.cta.href}
                      target={c.cta.href.startsWith("http") ? "_blank" : undefined}
                      rel={c.cta.href.startsWith("http") ? "noreferrer" : undefined}
                    >
                      {c.cta.label}
                    </a>
                  </Button>
                </CardFooter>
              </Card>
            </Reveal>
          ))}
        </div>
      </Section>
    </>
  );
}

// web/platform/src/components/qwik/pages/company.tsx
import { component$, useVisibleTask$ } from "@builder.io/qwik";

import { Label, LinearGradient } from "../components/text.tsx";

import { BackgroundVideo } from "../components/video.tsx";

const _cards = [
  {
    title: "Media Kit",
    description:
      "Download our media kit for logos, branding guidelines, and other resources.",
    linkTitle: "Download",
    link: "https://www.google.com/url?q=https://www.google.com/url?q%3Dhttps://drive.google.com/drive/folders/1fNmr4IpIaaiej6yKr1t0ispbXOaCVVTa?usp%253Dsharing%26amp;sa%3DD%26amp;source%3Deditors%26amp;ust%3D1723017295224121%26amp;usg%3DAOvVaw2K4tnmOdf37pPSQpeq0YIG&sa=D&source=docs&ust=1723017295247588&usg=AOvVaw1NaQYPBuTBwCIVNd6KkL0l",
  },
  {
    title: "General inquiries",
    description: "Reach out to us with any questions or comments you may have.",
    linkTitle: "Contact",
    link: "mailto:contact@nativelink.com",
  },
  {
    title: "Sales inquiries",
    description:
      "Interested in learning more about NativeLink?  Contact our sales team for more information.",
    linkTitle: "Contact",
    link: "mailto:contact@nativelink.com",
  },
];

const CompanyHero = component$(() => {
  return (
    <div class="relative w-full flex flex-col md:flex-row  md:gap-14 justify-center items-center ">

      <div class="px-8 z-10 gap-10 flex flex-col md:w-[650px] ">
        <div class="pr-8">
          <LinearGradient
            text="NativeLink is built by Trace Machina"
            class="text-4xl md:text-5xl text-left pr-10"
          />
        </div>
        <span class="test-base">
          At Trace Machina, our mission is to revolutionize the development of
          complex systems by providing cutting-edge tools that drastically
          reduce costs.
        </span>
        <span class="text-sm text-muted">
          We empower engineers to build the future of technology by making
          advanced build and simulation processes as intuitive and efficient as
          web development. Our commitment is to deliver innovative solutions
          that enable seamless task execution across any environment, ensuring
          that developers can focus on creating transformative technologies that
          drive progress and safety.
        </span>
      </div>
      <picture class="z-10 py-14 w-full md:w-[650px] flex justify-center items-center">
        <img
          src="https://nativelink-cdn.s3.us-east-1.amazonaws.com/tracemachina_logo.webp"
          alt=""
          class="w-3/4"
        />
      </picture>
    </div>
  );
});

const CompanyContact = component$(() => {
  return (
    <div class="flex px-8 flex-col justify-center items-center gap-5">
      <Label text="Get in Touch" class="text-base w-1/2" />
      <div>
        <LinearGradient
          text="Have questions or need assistance?"
          class="text-base text-center"
        />
        <LinearGradient
          text=" Contact us for general inquiries or sales inquiries."
          class="text-base text-center"
        />
      </div>
    </div>
  );
});

const CompanyCards = component$(() => {
  return (
    <div class="flex px-8 flex-col justify-start md:justify-stretch items-center gap-5 pb-24">
      {_cards.map((card) => (
        <div
          class="shadow-md w-full md:w-full md:flex-row flex flex-col md:justify-between justify-start md:items-center items-start gap-3 rounded-lg py-8 px-10 border border-solid border-black/10"
          key={card.title}
        >
          <div class="flex flex-col gap-2">
            <h2 class="text-2xl font-thin">{card.title}</h2>
            <p class="text-muted pr-24">{card.description}</p>
          </div>
          <a
            href={card.link}
            class="text-black no-underline! bg-white border-2 border-black px-8 py-2 rounded-xl hover:bg-black hover:text-white transition-colors"
            target="_blank"
            rel="noopener noreferrer"
          >
            {card.linkTitle}
          </a>
        </div>
      ))}
    </div>
  );
});

export const CompanyPage = component$(() => {
  useVisibleTask$(() => {
    console.info("About Trace Machina");
  });

  return (
    <main class="flex w-full w-screen flex-col pt-24 items-start justify-start text-black">
      <div class="gap-10 flex w-full flex-col justify-center items-center">
        <CompanyHero />
        <CompanyContact />
        <CompanyCards />
      </div>
    </main>
  );
});
