// web/apps/web/app/company/page.tsx
import {
  Button,
  Card,
  CardBody,
  CardFooter,
  CardHeader,
  CardTitle,
  Eyebrow,
  Reveal,
  Section,
} from "@nativelink/ui";

export const metadata = { title: "Company" };

const values = [
  {
    title: "Engineer like it matters.",
    body: "We work on infrastructure that other engineers depend on. The bar is correctness, then performance, then everything else.",
  },
  {
    title: "Default to open.",
    body: "Most of the monorepo is FSL-1.1-Apache-2.0. We keep the code visible, and we sell support, operations, and commercial terms for selected modules.",
  },
  {
    title: "Speed is a feature.",
    body: "Slow builds cost developer time, focus, and willpower. We measure ourselves in milliseconds, not feature checkboxes.",
  },
  {
    title: "Hard problems, kindly.",
    body: "Distributed systems are unforgiving; humans don't have to be. We ship rigorous code with patient code review.",
  },
];

const contactCards = [
  {
    title: "Media kit",
    body: "Logos, branding guidelines, and approved press resources.",
    cta: {
      label: "Download",
      href: "https://drive.google.com/drive/folders/1fNmr4IpIaaiej6yKr1t0ispbXOaCVVTa?usp=sharing",
    },
    variant: "outline" as const,
  },
  {
    title: "General inquiries",
    body: "Have a question or comment? We'd love to hear from you.",
    cta: { label: "Contact us", href: "mailto:contact@tracemachina.com" },
    variant: "outline" as const,
  },
  {
    title: "Sales inquiries",
    body: "Curious if NativeLink fits your team? Our sales engineers can help.",
    cta: { label: "Talk to sales", href: "mailto:contact@tracemachina.com" },
    variant: "primary" as const,
  },
];

export default function CompanyPage() {
  return (
    <>
      {/* HERO */}
      <section className="relative overflow-hidden">
        <div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[600px] bg-[radial-gradient(ellipse_1000px_500px_at_50%_-10%,rgb(var(--nl-color-brand)/0.16),transparent_70%)]" />
        <Section width="default" className="pt-24 pb-16 md:pt-32">
          <Reveal>
            <div className="mx-auto max-w-[920px] text-center">
              <Eyebrow className="mb-5">Company</Eyebrow>
              <h1 className="text-balance text-[44px] font-semibold leading-[1.02] tracking-[-0.04em] md:text-[68px]">
                Accelerating the{" "}
                <span className="bg-gradient-to-r from-brand to-brand-strong bg-clip-text text-transparent">
                  machine age
                </span>
                .
              </h1>
              <p className="mx-auto mt-6 max-w-[680px] text-[17px] leading-relaxed text-muted-foreground md:text-lg">
                NativeLink is built by Trace Machina. Our mission is to accelerate the
                reindustrialization of the world by making advanced build and simulation processes
                that move at machine speed.
              </p>
            </div>
          </Reveal>
        </Section>
      </section>

      {/* MISSION */}
      <Section width="narrow" className="pb-24">
        <Reveal>
          <div className="space-y-6 text-balance text-center text-base leading-relaxed text-muted-foreground md:text-lg">
            <p className="text-2xl font-semibold leading-[1.3] tracking-[-0.02em] text-foreground md:text-3xl">
              Mission: Accelerate the progress of humanity in the machine age.
            </p>
            <p>
              Our products amplify the rate at which companies can innovate across mission-critical
              industries — from semiconductors and advanced robotics to autonomous vehicles, AI
              research, life sciences, and financial services.
            </p>
            <p>
              Our commitment is to amplify execution across any environment, ensuring that
              developers can focus on creating transformative technologies that drive forward
              progress on behalf of humanity.
            </p>
          </div>
        </Reveal>
      </Section>

      {/* VALUES */}
      <Section width="default" className="border-y border-border/60 bg-surface-elevated/40 py-24">
        <Reveal>
          <div className="mb-14 max-w-[600px]">
            <Eyebrow className="mb-4">Values</Eyebrow>
            <h2 className="text-balance text-4xl font-semibold leading-[1.05] tracking-[-0.03em] md:text-5xl">
              How we work.
            </h2>
          </div>
        </Reveal>
        <div className="grid gap-5 md:grid-cols-2">
          {values.map((v, i) => (
            <Reveal key={v.title} delay={i * 0.06}>
              <div className="group h-full rounded-2xl border border-border bg-surface p-8 transition-colors hover:border-brand/40">
                <div className="mb-6 inline-flex h-10 w-10 items-center justify-center rounded-xl bg-brand-soft font-mono text-sm font-semibold text-brand">
                  0{i + 1}
                </div>
                <h3 className="text-2xl font-semibold leading-tight tracking-tight text-foreground">
                  {v.title}
                </h3>
                <p className="mt-3 text-[15px] leading-relaxed text-muted-foreground">{v.body}</p>
              </div>
            </Reveal>
          ))}
        </div>
      </Section>

      {/* CONTACT */}
      <Section width="default" className="border-t border-border/60 bg-surface-elevated/40 py-24">
        <Reveal>
          <div className="mx-auto mb-12 max-w-[680px] text-center">
            <Eyebrow className="mb-4">Get in touch</Eyebrow>
            <h2 className="text-balance text-4xl font-semibold leading-[1.05] tracking-[-0.03em] md:text-5xl">
              Have questions or need assistance?
            </h2>
            <p className="mt-5 text-base leading-relaxed text-muted-foreground md:text-lg">
              Reach out for general inquiries, sales conversations, or anything else — we usually
              reply within a day.
            </p>
          </div>
        </Reveal>
        <div className="grid gap-5 md:grid-cols-3">
          {contactCards.map((c, i) => (
            <Reveal key={c.title} delay={i * 0.05}>
              <Card
                variant={c.variant === "primary" ? "featured" : "default"}
                className="flex h-full flex-col"
              >
                <CardHeader>
                  <CardTitle>{c.title}</CardTitle>
                </CardHeader>
                <CardBody>{c.body}</CardBody>
                <CardFooter className="mt-auto pt-8">
                  <Button asChild variant={c.variant} size="md" className="w-full">
                    <a
                      href={c.cta.href}
                      target={c.cta.href.startsWith("http") ? "_blank" : undefined}
                      rel={c.cta.href.startsWith("http") ? "noreferrer" : undefined}
                    >
                      {c.cta.label}
                    </a>
                  </Button>
                </CardFooter>
              </Card>
            </Reveal>
          ))}
        </div>
      </Section>
    </>
  );
}

// web/platform/src/components/qwik/pages/company.tsx
import { component$, useVisibleTask$ } from "@builder.io/qwik";

import { Label, LinearGradient } from "../components/text.tsx";

import { BackgroundVideo } from "../components/video.tsx";

const _cards = [
  {
    title: "Media Kit",
    description:
      "Download our media kit for logos, branding guidelines, and other resources.",
    linkTitle: "Download",
    link: "https://www.google.com/url?q=https://www.google.com/url?q%3Dhttps://drive.google.com/drive/folders/1fNmr4IpIaaiej6yKr1t0ispbXOaCVVTa?usp%253Dsharing%26amp;sa%3DD%26amp;source%3Deditors%26amp;ust%3D1723017295224121%26amp;usg%3DAOvVaw2K4tnmOdf37pPSQpeq0YIG&sa=D&source=docs&ust=1723017295247588&usg=AOvVaw1NaQYPBuTBwCIVNd6KkL0l",
  },
  {
    title: "General inquiries",
    description: "Reach out to us with any questions or comments you may have.",
    linkTitle: "Contact",
    link: "mailto:contact@nativelink.com",
  },
  {
    title: "Sales inquiries",
    description:
      "Interested in learning more about NativeLink?  Contact our sales team for more information.",
    linkTitle: "Contact",
    link: "mailto:contact@nativelink.com",
  },
];

const CompanyHero = component$(() => {
  return (
    <div class="relative w-full flex flex-col md:flex-row  md:gap-14 justify-center items-center ">

      <div class="px-8 z-10 gap-10 flex flex-col md:w-[650px] ">
        <div class="pr-8">
          <LinearGradient
            text="NativeLink is built by Trace Machina"
            class="text-4xl md:text-5xl text-left pr-10"
          />
        </div>
        <span class="test-base">
          At Trace Machina, our mission is to revolutionize the development of
          complex systems by providing cutting-edge tools that drastically
          reduce costs.
        </span>
        <span class="text-sm text-muted">
          We empower engineers to build the future of technology by making
          advanced build and simulation processes as intuitive and efficient as
          web development. Our commitment is to deliver innovative solutions
          that enable seamless task execution across any environment, ensuring
          that developers can focus on creating transformative technologies that
          drive progress and safety.
        </span>
      </div>
      <picture class="z-10 py-14 w-full md:w-[650px] flex justify-center items-center">
        <img
          src="https://nativelink-cdn.s3.us-east-1.amazonaws.com/tracemachina_logo.webp"
          alt=""
          class="w-3/4"
        />
      </picture>
    </div>
  );
});

const CompanyContact = component$(() => {
  return (
    <div class="flex px-8 flex-col justify-center items-center gap-5">
      <Label text="Get in Touch" class="text-base w-1/2" />
      <div>
        <LinearGradient
          text="Have questions or need assistance?"
          class="text-base text-center"
        />
        <LinearGradient
          text=" Contact us for general inquiries or sales inquiries."
          class="text-base text-center"
        />
      </div>
    </div>
  );
});

const CompanyCards = component$(() => {
  return (
    <div class="flex px-8 flex-col justify-start md:justify-stretch items-center gap-5 pb-24">
      {_cards.map((card) => (
        <div
          class="shadow-md w-full md:w-full md:flex-row flex flex-col md:justify-between justify-start md:items-center items-start gap-3 rounded-lg py-8 px-10 border border-solid border-black/10"
          key={card.title}
        >
          <div class="flex flex-col gap-2">
            <h2 class="text-2xl font-thin">{card.title}</h2>
            <p class="text-muted pr-24">{card.description}</p>
          </div>
          <a
            href={card.link}
            class="text-black no-underline! bg-white border-2 border-black px-8 py-2 rounded-xl hover:bg-black hover:text-white transition-colors"
            target="_blank"
            rel="noopener noreferrer"
          >
            {card.linkTitle}
          </a>
        </div>
      ))}
    </div>
  );
});

export const CompanyPage = component$(() => {
  useVisibleTask$(() => {
    console.info("About Trace Machina");
  });

  return (
    <main class="flex w-full w-screen flex-col pt-24 items-start justify-start text-black">
      <div class="gap-10 flex w-full flex-col justify-center items-center">
        <CompanyHero />
        <CompanyContact />
        <CompanyCards />
      </div>
    </main>
  );
});
